apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-run-
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: app-repo
    resourceRef:
      name: app-repo
  workspaces:
  - name: build-workspace
    persistentVolumeClaim:
      claimName: build-workspace-pvc
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-m2-repo-pvc
