- op: add
  path: /subjects/-
  value:
    kind: ServiceAccount
    name: petclinic
    namespace: petclinic-dev
- op: add
  path: /subjects/-
  value:
    kind: ServiceAccount
    name: petclinic
    namespace: petclinic-uat