apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth
  annotations:
    tekton.dev/git-0: https://github.com 
type: kubernetes.io/basic-auth
stringData:
  username: notmyusername
  password: notmypassword