apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-m2-repo-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
